name: Validate
on:
  pull_request:
    types: synchronize

jobs:
  diff:
    name: Check diff
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
            ${{ runner.OS }}-

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Decrypt config
        run: npm run decrypt-config -- --passphrase="$ENCRYPT_PASSPHRASE" maildog.config.json.gpg
        env:
          ENCRYPT_PASSPHRASE: ${{ secrets.ENCRYPT_PASSPHRASE }}

      - name: Log CDK diff result
        run: npx ts-node --prefer-ts-exts scripts/logCdkDiffResult.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
